# Generated by Django 3.1.5 on 2021-02-20 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Product's name")),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="Product's price")),
            ],
        ),
    ]
