# Generated by Django 3.1.5 on 2021-02-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210220_2026'),
        ('products', '0002_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='cart.Cart'),
        ),
    ]
