# Generated by Django 3.1.5 on 2021-02-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210220_2026'),
        ('products', '0003_auto_20210220_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='products', to='cart.Cart'),
        ),
    ]
